# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: redis-operator

resources:
- namespace.yaml
- redis-operator

components:
- ../../../shared/components/restricted-pod-security
- ../../../shared/components/k8s-digester

patches:
- path: patches/operator-group-id.yaml
