name: setup
description: setup

runs:
  using: composite
  steps:
  - name: Install Nix
    uses: nixbuild/nix-quick-install-action@9f63be77f412a248c9d9a65a4c82cf066cdf8f0c # v35
  - name: Load Nix environment
    uses: nicknovitski/nix-develop@9be7cfb4b10451d3390a75dc18ad0465bed4932a # v1.2.1
    with:
      arguments: .#ci
  - name: Cache Task checksums
    uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6.0.0
    with:
      path: ./.task/
      key: .task-${{ github.ref_name }}-${{ hashFiles('**/*') }}
      restore-keys: |
        .task-${{ github.ref_name }}-
        .task-
