apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: enabled
  name: keycloak-db
  namespace: keycloak
spec:
  affinity:
    podAntiAffinityType: required
  bootstrap:
    recovery:
      database: keycloak
      source: origin
  externalClusters:
  - name: origin
    plugin:
      name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: keycloak-db
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4-standard-trixie@sha256:4e4ac3fb2c914cfb44f80f0b8be8aa550e83b80bf5220df49c3a8780c1f79bc8
  instances: 3
  plugins:
  - isWALArchiver: true
    name: barman-cloud.cloudnative-pg.io
    parameters:
      barmanObjectName: keycloak-db
  storage:
    size: 100Gi
    storageClass: ssd-r1
