apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
  labels:
    advertise: bgp
  name: cilium-bgp-service-advertisements
spec:
  advertisements:
  - advertisementType: PodCIDR
  - advertisementType: Service
    selector:
      matchExpressions:
      - key: somekey
        operator: NotIn
        values:
        - never-used-value
    service:
      addresses:
      - ClusterIP
      - LoadBalancerIP
