apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: redis-operator
    app.kubernetes.io/name: redis-operator
    app.kubernetes.io/part-of: redis-operator
  name: redis-operator
  namespace: redis-operator
