apiVersion: v1
kind: Service
metadata:
  annotations:
    kapp.k14s.io/disable-label-scoping: ""
  name: talos
  namespace: test-sandbox
spec:
  clusterIP: None
  selector:
    kubevirt.io/vmpool: controlplane
