apiVersion: v1
kind: Secret
metadata:
  name: talosconfig
  namespace: test-sandbox
stringData:
  talosconfig: |
    context: talos
    contexts:
      talos:
        endpoints:
        - controlplane-0.talos
        nodes:
        - controlplane-0
        ca: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQekNCOHFBREFnRUNBaEVBc1A5VjA2emZzcC9WdzBvNHQ4OTMyekFGQmdNclpYQXdFREVPTUF3R0ExVUUKQ2hNRmRHRnNiM013SGhjTk1qVXdNakl4TURNME56TTNXaGNOTXpVd01qRTVNRE0wTnpNM1dqQVFNUTR3REFZRApWUVFLRXdWMFlXeHZjekFxTUFVR0F5dGxjQU1oQUR3YWh5Mm5seFEyYnJ4aG5kZWNvenJlYmg1Y0hjNURiS0VYCi9peWFpUHgvbzJFd1h6QU9CZ05WSFE4QkFmOEVCQU1DQW9Rd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUcKQ0NzR0FRVUZCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkx1SHlHUVFTYnlWS2prVwoxQUR0eEpJbFB6L3hNQVVHQXl0bGNBTkJBQkx5Qld5TlRlVWFTZjM2MXFoMkJCYTFxWitWVkZjbWhqUkprWU9PCndHRm5SMjQ2Y21IY1g3TWpUNW5Jajk3enZMaFY4NmZnUUcvSGp3MVNNYlFCNmdvPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJLVENCM0tBREFnRUNBaEVBeFRjY1N4MFFFMGhYZVdVQWFnb3g2REFGQmdNclpYQXdFREVPTUF3R0ExVUUKQ2hNRmRHRnNiM013SGhjTk1qVXdNakl4TURNME56TTNXaGNOTWpZd01qSXhNRE0wTnpNM1dqQVRNUkV3RHdZRApWUVFLRXdodmN6cGhaRzFwYmpBcU1BVUdBeXRsY0FNaEFObmxKdDhELys5Vnk4Y00zS0VpQkFRMEJxM3J6aDZGCjBSNHArWHk0VGRJem8wZ3dSakFPQmdOVkhROEJBZjhFQkFNQ0I0QXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0h3WURWUjBqQkJnd0ZvQVV1NGZJWkJCSnZKVXFPUmJVQU8zRWtpVS9QL0V3QlFZREsyVndBMEVBeE9ZegpJdGpUN1BTQVd5dlFkaldDbXZ6TnFwOUpHS2JVa2hFNFRzTzRWaEVmQ1I1OVFNR1dkL1VUNlUxS0ZQa2JPZ1RHCkYzME5FY1ZOWlpTNDlHRnVCUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        key: LS0tLS1CRUdJTiBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0KTUM0Q0FRQXdCUVlESzJWd0JDSUVJTmxpendySnBBOW1Temg1ZVZHdDdBb0JWRlY3bjkyYzFYK3dwcFhRVDdXQgotLS0tLUVORCBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0K
type: Opaque
