# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- ../../../shared/components/strip-helm-labels

helmCharts:
- name: sealed-secrets
  repo: https://bitnami-labs.github.io/sealed-secrets
  releaseName: sealed-secrets
  namespace: kube-system
  version: 2.18.0
  includeCRDs: true
  valuesInline:
    fullnameOverride: sealed-secrets-controller
    image:
      registry: ghcr.io
      repository: bitnami-labs/sealed-secrets-controller

images:
- name: ghcr.io/bitnami-labs/sealed-secrets-controller
  newTag: 0.36.6@sha256:3cf5db7d1722710de8b9216c821cad2ff52e0d284843b205a86ce99af21b05a3
