# yaml-language-server: $schema=../../../schemas/piraeus.io/linstorcluster_v1.json
apiVersion: piraeus.io/v1
kind: LinstorCluster
metadata:
  name: linstorcluster
spec:
  nodeSelector:
    seigra.net/storage: "true"
  nodeAffinity:
    nodeSelectorTerms:
    - matchExpressions:
      - key: linstor.seigra.net/evacuate
        operator: DoesNotExist
  linstorPassphraseSecret: linstorcluster-passphrase
  highAvailabilityController:
    podTemplate:
      spec:
        containers:
        - name: ha-controller
          args:
          - /agent
          - --v=1
          - --disable-node-taints=true
  internalTLS:
    certManager:
      name: linstor-internal-ca
      kind: Issuer
  properties:
  - name: Luks/AllowDiscards
    value: "true"
  - name: DrbdOptions/Net/max-buffers
    value: "40960"
  - name: DrbdOptions/Net/rcvbuf-size
    value: "10485760"
  - name: DrbdOptions/Net/sndbuf-size
    value: "10485760"
  - name: DrbdOptions/PeerDevice/c-fill-target
    value: "1024"
  - name: DrbdOptions/PeerDevice/c-plan-ahead
    value: "20"
  - name: DrbdOptions/auto-diskful
    value: "10"
  - name: StorDriver/LuksFormatOptions
    value: --offset 32768
  - name: AllowMixingStoragePoolDriver
    value: "true"
  - name: DrbdOptions/Net/protocol
    value: B
