# yaml-language-server: $schema=../../../schemas/piraeus.io/linstorsatelliteconfiguration_v1.json
apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: defaults
spec:
  deletionPolicy: Evacuate
