# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- database.yaml
- redis
- tika
- gotenberg
- paperless-ngx

components:
- ../../../shared/components/crd-configurations

images:
- name: ghcr.io/valkey-io/valkey
  newTag: 9.0.0-alpine3.22@sha256:bef37d06d4856710973ee31dd1eac1482e4c8e6e7b847f999ad25433e646587b
- name: docker.io/apache/tika
  newTag: 3.3.1.0@sha256:90b7fa1dc018434075fce9e1d9b88b1e3d0ea6979d0cf86e116c79a8073ae973
- name: docker.io/gotenberg/gotenberg
  newTag: 8.33.0@sha256:bddd8ea9d076e2d08b6ddaa6efae6403185202c6dab65a6488ed0a6923d6d8e8
- name: ghcr.io/paperless-ngx/paperless-ngx
  newTag: 2.20.15@sha256:6c86cad803970ea782683a8e80e7403444c5bf3cf70de63b4d3c8e87500db92f
- name: ghcr.io/cloudnative-pg/postgresql
  newTag: 18.4-standard-trixie@sha256:1e9b7f86a108b8eb472f52b59fc085aafee4cb3841484727ad67c020a8935a86

labels:
- pairs:
    app.kubernetes.io/instance: paperless-ngx
    app.kubernetes.io/part-of: paperless-ngx
  includeSelectors: true
  includeTemplates: true
