# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- database.yaml
- redis
- tika
- gotenberg
- paperless-ngx

components:
- ../../../shared/components/crd-configurations

images:
- name: ghcr.io/valkey-io/valkey
  newTag: 9.0.0-alpine3.22@sha256:bef37d06d4856710973ee31dd1eac1482e4c8e6e7b847f999ad25433e646587b
- name: docker.io/apache/tika
  newTag: 3.3.1.0@sha256:90b7fa1dc018434075fce9e1d9b88b1e3d0ea6979d0cf86e116c79a8073ae973
- name: docker.io/gotenberg/gotenberg
  newTag: 8.34.0@sha256:67097317623a503ba2a6a7e9ae8db6929a1f7e1bbd88077bacf2d325fbdab923
- name: ghcr.io/paperless-ngx/paperless-ngx
  newTag: 3.0.2@sha256:fef384c955d2ec2acf1bd0882ffc195ecc170266c803dfe28b79df6deabb3569
- name: ghcr.io/cloudnative-pg/postgresql
  newTag: 18.4-standard-trixie@sha256:4e4ac3fb2c914cfb44f80f0b8be8aa550e83b80bf5220df49c3a8780c1f79bc8

labels:
- pairs:
    app.kubernetes.io/instance: paperless-ngx
    app.kubernetes.io/part-of: paperless-ngx
  includeSelectors: true
  includeTemplates: true
