apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: mariadb-operator
    app.kubernetes.io/name: mariadb-operator
  name: mariadb-operator
  namespace: mariadb-system
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: mariadb-operator
      app.kubernetes.io/name: mariadb-operator
  template:
    metadata:
      annotations:
        checksum/config: 10be48c9c0a7dafd4b6445c4ee336a172205816900e1266de69fe2dc031bc17f
      labels:
        app.kubernetes.io/instance: mariadb-operator
        app.kubernetes.io/name: mariadb-operator
    spec:
      automountServiceAccountToken: true
      containers:
      - args:
        - --metrics-addr=:8080
        - --log-level=INFO
        env:
        - name: CLUSTER_NAME
          value: cluster.local
        - name: MARIADB_OPERATOR_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: MARIADB_OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MARIADB_OPERATOR_SA_PATH
          value: /var/run/secrets/kubernetes.io/serviceaccount/token
        envFrom:
        - configMapRef:
            name: mariadb-operator-env
        image: ghcr.io/mariadb-operator/mariadb-operator:26.6.0@sha256:a5e17b48f08ef02cda59a5b0ed68a18ae5e0f820129ac391fa220ea117aebd6c
        imagePullPolicy: IfNotPresent
        name: controller
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
      serviceAccountName: mariadb-operator
      terminationGracePeriodSeconds: 10
