apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-keycloak
spec:
  package: ghcr.io/crossplane-contrib/provider-keycloak:v2.16.1@sha256:f7a4fb231f264ec3fb9d7983dadd3bbd98640230c426808a1d1cc993b508ce8d
  runtimeConfigRef:
    name: provider-keycloak
