apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-keycloak
spec:
  package: ghcr.io/crossplane-contrib/provider-keycloak:v2.22.0@sha256:ab114efe9f72d6c2f0e212d4fe8646d6b736fa1d43a065783ff33ae821096e50
  runtimeConfigRef:
    name: provider-keycloak
