# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.36.1/storageclass.json
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd-r1
  annotations:
    argocd.argoproj.io/sync-options: Force=true,Replace=true
provisioner: linstor.csi.linbit.com
parameters:
  linstor.csi.linbit.com/resourceGroup: ssd-r1
  linstor.csi.linbit.com/storagePool: ssd
  linstor.csi.linbit.com/layerList: storage
  linstor.csi.linbit.com/allowRemoteVolumeAccess: "false"
  property.linstor.csi.linbit.com/Aux/linstor.csi.linbit.com/evacuation-action: Delete
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.36.1/storageclass.json
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd-r2
  annotations:
    argocd.argoproj.io/sync-options: Force=true,Replace=true
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: linstor.csi.linbit.com
parameters:
  linstor.csi.linbit.com/autoPlace: "2"
  linstor.csi.linbit.com/resourceGroup: ssd-r2
  linstor.csi.linbit.com/storagePool: ssd
  linstor.csi.linbit.com/layerList: drbd storage
  property.linstor.csi.linbit.com/Aux/linstor.csi.linbit.com/evacuation-action: None
  property.linstor.csi.linbit.com/DrbdOptions/PeerDevice/c-max-rate: "532480"
  property.linstor.csi.linbit.com/DrbdOptions/PeerDevice/c-min-rate: "177493"
  property.linstor.csi.linbit.com/DrbdOptions/PeerDevice/resync-rate: "177493"
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
