# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: headlamp

resources:
- namespace.yaml
- gateway.yaml
- httproute.yaml

components:
- ../../../shared/components/strip-helm-labels
- ../../../shared/components/restricted-pod-security

helmCharts:
- name: headlamp
  repo: https://kubernetes-sigs.github.io/headlamp
  releaseName: headlamp
  version: 0.43.0
  namespace: headlamp
  valuesInline:
    config:
      oidc:
        secret:
          create: false
        clientID: kubernetes
        issuerURL: https://auth.seigra.net/realms/home
        scopes: email,profile
        callbackURL: https://headlamp.seigra.net/oidc-callback
    volumes:
    - name: plugins-dir
      emptyDir: {}
    volumeMounts:
    - name: plugins-dir
      mountPath: /headlamp/plugins
    initContainers:
    - name: install-cert-manager-plugin
      # renovate: datasource=docker depName=ghcr.io/headlamp-k8s/headlamp-plugin-cert-manager
      image: ghcr.io/headlamp-k8s/headlamp-plugin-cert-manager:v0.1.0@sha256:d7d0321a90c0347e2e4f9f7e362ecaa10a36592cc5ac8fd1514df11c476b43fe
      command: ["/bin/sh", "-c", "cp -r /plugins/* /headlamp/plugins/"]
      volumeMounts:
      - name: plugins-dir
        mountPath: /headlamp/plugins
      securityContext:
        runAsUser: 100
        runAsGroup: 101
    - name: install-kubevirt-plugin
      # renovate: datasource=docker depName=ghcr.io/naval-group/headlamp-kubevirt
      image: ghcr.io/naval-group/headlamp-kubevirt:sha-bd4b26f@sha256:f31259becc8b36178622c77319513acb9eaf5c583217a2244a328e7615701f97
      command: ["/bin/sh", "-c", "cp -r /plugins/* /headlamp/plugins/"]
      volumeMounts:
      - name: plugins-dir
        mountPath: /headlamp/plugins
      securityContext:
        runAsUser: 100
        runAsGroup: 101
    - name: install-external-secrets-operator-plugin
      command: ["/bin/sh", "-c", "cp -r /plugins/* /headlamp/plugins/"]
      # renovate: datasource=docker depName=ghcr.io/magohl/external-secrets-operator-headlamp-plugin
      image: ghcr.io/magohl/external-secrets-operator-headlamp-plugin:0.1.0-beta7@sha256:7a48e51b90337ff3b5bf74e326047fc5886257b316be7c5a17e707dcce4cbd64
      volumeMounts:
      - name: plugins-dir
        mountPath: /headlamp/plugins
      securityContext:
        runAsUser: 100
        runAsGroup: 101

patches:
- path: patches/oidc-use-pkce.yaml
  target:
    kind: Deployment
    name: headlamp
