# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/v3.1.14/pkg/config/schemas/talconfig.json
clusterName: production
# renovate: datasource=github-releases depName=siderolabs/talos
talosVersion: v1.14.0-alpha.2
# renovate: datasource=github-releases depName=kubernetes/kubernetes
kubernetesVersion: v1.36.1
endpoint: https://10.1.4.10:6443
nodes:
- hostname: production-controlplane-1
  ipAddress: 10.1.4.11
  installDisk: /dev/nvme0n1
  controlPlane: true
  nodeLabels:
    seigra.net/storage: "true"
  networkInterfaces:
  - interface: enp2s0
    vlans:
    - vlanId: 2
    - vlanId: 4
    - vlanId: 10
  - interface: br-cluster
    dhcp: true
    vip:
      ip: 10.1.4.10
    bridge:
      interfaces:
      - enp2s0.4
  - interface: br-server
    bridge:
      interfaces:
      - enp2s0.2
  - interface: br-lan
    bridge:
      interfaces:
      - enp2s0.10
  volumes:
  - name: STATE
    encryption:
      provider: luks2
      keys:
      - tpm: {}
        slot: 0
  - name: EPHEMERAL
    encryption:
      provider: luks2
      keys:
      - tpm: {}
        slot: 0
  patches:
  - '@clusterconfig/patches/linstor-ssd-sata-vol1.yaml'
- hostname: production-controlplane-2
  ipAddress: 10.1.4.12
  installDisk: /dev/nvme0n1
  controlPlane: true
  nodeLabels:
    seigra.net/storage: "true"
  networkInterfaces:
  - interface: enp2s0
    vlans:
    - vlanId: 2
    - vlanId: 4
    - vlanId: 10
  - interface: br-cluster
    dhcp: true
    vip:
      ip: 10.1.4.10
    bridge:
      interfaces:
      - enp2s0.4
  - interface: br-server
    bridge:
      interfaces:
      - enp2s0.2
  - interface: br-lan
    bridge:
      interfaces:
      - enp2s0.10
  volumes:
  - name: STATE
    encryption:
      provider: luks2
      keys:
      - tpm: {}
        slot: 0
  - name: EPHEMERAL
    encryption:
      provider: luks2
      keys:
      - tpm: {}
        slot: 0
  patches:
  - '@clusterconfig/patches/linstor-ssd-sata-vol1.yaml'
- hostname: production-controlplane-3
  ipAddress: 10.1.4.13
  installDisk: /dev/nvme0n1
  controlPlane: true
  nodeLabels:
    seigra.net/storage: "true"
  networkInterfaces:
  - interface: enp2s0
    vlans:
    - vlanId: 2
    - vlanId: 4
    - vlanId: 10
  - interface: br-cluster
    dhcp: true
    vip:
      ip: 10.1.4.10
    bridge:
      interfaces:
      - enp2s0.4
  - interface: br-server
    bridge:
      interfaces:
      - enp2s0.2
  - interface: br-lan
    bridge:
      interfaces:
      - enp2s0.10
  volumes:
  - name: STATE
    encryption:
      provider: luks2
      keys:
      - tpm: {}
        slot: 0
  - name: EPHEMERAL
    encryption:
      provider: luks2
      keys:
      - tpm: {}
        slot: 0
  patches:
  - '@clusterconfig/patches/linstor-ssd-sata-vol1.yaml'
allowSchedulingOnControlPlanes: true
controlPlane:
  talosImageURL: factory.talos.dev/installer-secureboot/3e3e89f3a168df62f7b68e56926830e477106f1015a9ce74a95a5f13c3ca52d0
  patches:
  - '@clusterconfig/patches/containerd-config.yaml'
  - '@clusterconfig/patches/disable-hostdns.yaml'
  - '@clusterconfig/patches/disable-proxy.yaml'
  - '@clusterconfig/patches/kernel-modules.yaml'
  - '@clusterconfig/patches/metrics-scraping.yaml'
  - '@clusterconfig/patches/no-cni.yaml'
  - '@clusterconfig/patches/oidc.yaml'
  - '@clusterconfig/patches/parallel-image-pulls.yaml'
  - '@clusterconfig/patches/pod-security.yaml'
  - '@clusterconfig/patches/registry-mirrors.yaml'
