apiVersion: v1alpha1
kind: KubeAuthenticationConfig
configuration:
  anonymous:
    conditions:
    - path: /livez
    - path: /readyz
    - path: /healthz
    enabled: true
  jwt:
  - issuer:
      url: https://auth.seigra.net/realms/home
      audiences:
      - kubernetes
    claimMappings:
      username:
        claim: email
        prefix: ""
      groups:
        claim: groups
        prefix: ""
