apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Force=true,Replace=true
  name: production-controlplane-2-pools
spec:
  nodeSelector:
    kubernetes.io/hostname: production-controlplane-2
  storagePools:
  - lvmThinPool: {}
    name: ssd
    source:
      hostDevices:
      - /dev/disk/by-id/dm-name-luks2-r-linstor-ssd-sata-vol1
