allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Force=true,Replace=true
    storageclass.kubernetes.io/is-default-class: "true"
  name: ssd-r2
parameters:
  linstor.csi.linbit.com/autoPlace: "2"
  linstor.csi.linbit.com/layerList: drbd storage
  linstor.csi.linbit.com/resourceGroup: ssd-r2
  linstor.csi.linbit.com/storagePool: ssd
  property.linstor.csi.linbit.com/Aux/linstor.csi.linbit.com/evacuation-action: None
  property.linstor.csi.linbit.com/DrbdOptions/PeerDevice/c-max-rate: "532480"
  property.linstor.csi.linbit.com/DrbdOptions/PeerDevice/c-min-rate: "177493"
  property.linstor.csi.linbit.com/DrbdOptions/PeerDevice/resync-rate: "177493"
provisioner: linstor.csi.linbit.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
