allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Force=true,Replace=true
  name: ssd-r1
parameters:
  linstor.csi.linbit.com/allowRemoteVolumeAccess: "true"
  linstor.csi.linbit.com/encryption: "true"
  linstor.csi.linbit.com/layerList: drbd luks storage
  linstor.csi.linbit.com/resourceGroup: ssd-r1
  linstor.csi.linbit.com/storagePool: ssd
  property.linstor.csi.linbit.com/Aux/linstor.csi.linbit.com/evacuation-action: Delete
  property.linstor.csi.linbit.com/DrbdOptions/PeerDevice/c-max-rate: "532480"
  property.linstor.csi.linbit.com/DrbdOptions/PeerDevice/c-min-rate: "177493"
  property.linstor.csi.linbit.com/DrbdOptions/PeerDevice/resync-rate: "177493"
  property.linstor.csi.linbit.com/StorDriver/ZfscreateOptions: -o volblocksize=16k
provisioner: linstor.csi.linbit.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
