apiVersion: v1
kind: Secret
metadata:
  name: controlplane-userdata
  namespace: test-sandbox
stringData:
  userdata: |
    version: v1alpha1
    debug: false
    persist: true
    machine:
      type: controlplane
      token: 7bvw9w.unuydd839ioa0b3y
      ca:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQekNCOHFBREFnRUNBaEVBc1A5VjA2emZzcC9WdzBvNHQ4OTMyekFGQmdNclpYQXdFREVPTUF3R0ExVUUKQ2hNRmRHRnNiM013SGhjTk1qVXdNakl4TURNME56TTNXaGNOTXpVd01qRTVNRE0wTnpNM1dqQVFNUTR3REFZRApWUVFLRXdWMFlXeHZjekFxTUFVR0F5dGxjQU1oQUR3YWh5Mm5seFEyYnJ4aG5kZWNvenJlYmg1Y0hjNURiS0VYCi9peWFpUHgvbzJFd1h6QU9CZ05WSFE4QkFmOEVCQU1DQW9Rd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUcKQ0NzR0FRVUZCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkx1SHlHUVFTYnlWS2prVwoxQUR0eEpJbFB6L3hNQVVHQXl0bGNBTkJBQkx5Qld5TlRlVWFTZjM2MXFoMkJCYTFxWitWVkZjbWhqUkprWU9PCndHRm5SMjQ2Y21IY1g3TWpUNW5Jajk3enZMaFY4NmZnUUcvSGp3MVNNYlFCNmdvPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: LS0tLS1CRUdJTiBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0KTUM0Q0FRQXdCUVlESzJWd0JDSUVJQVlvUjdsWlZqWjRER3VGRnNROEliOTVtZFNYM2lsQ3llekNncGFRM3ZlQQotLS0tLUVORCBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0K
      certSANs:
      - controlplane-0.talos
      kubelet:
        image: ghcr.io/siderolabs/kubelet:v1.32.2
        defaultRuntimeSeccompProfileEnabled: true
        disableManifestsDirectory: true
      network:
        interfaces:
        - interface: eno1
          dhcp: true
      install:
        disk: /dev/vda
        image: factory.talos.dev/installer-secureboot/a13c1e1cdb9e135b5ae8ca3e977a5bee91bb4a503493d9204b6433239f462799:v1.9.4
        wipe: false
      features:
        rbac: true
        stableHostname: true
        apidCheckExtKeyUsage: true
        diskQuotaSupport: true
        kubePrism:
          enabled: true
          port: 7445
        hostDNS:
          enabled: true
          forwardKubeDNSToHost: true
      nodeLabels:
        node.kubernetes.io/exclude-from-external-load-balancers: ""
    cluster:
      id: WzrIW0xCN8tKuLmiPUC_u0BA4yePLZGIHFzz787_Hf4=
      secret: +yCqnUlpWh/hosoadAyaN8bXqu9qumGyTOzhE9vrkD0=
      controlPlane:
        endpoint: https://controlplane-0:6443
      clusterName: talos
      network:
        dnsDomain: cluster.local
        podSubnets:
        - 10.245.0.0/16
        serviceSubnets:
        - 10.112.0.0/12
      token: icd2bk.z8pnxekg7j194psw
      secretboxEncryptionSecret: 3OdehPZOi8bI1JluzeXFKdQf9IG0ecYEKLDNFOi7y5Y=
      ca:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpVENDQVMrZ0F3SUJBZ0lRVlBodS9NekhoVWtxd1BCTEtmNFkxakFLQmdncWhrak9QUVFEQWpBVk1STXcKRVFZRFZRUUtFd3ByZFdKbGNtNWxkR1Z6TUI0WERUSTFNREl5TVRBek5EY3pObG9YRFRNMU1ESXhPVEF6TkRjegpObG93RlRFVE1CRUdBMVVFQ2hNS2EzVmlaWEp1WlhSbGN6QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VICkEwSUFCTHBqV3E4T1BLVVpkMjF5eHJlRnhOV05zMHJwaS94QTdnc2hmeHB6U3hxOG1ab1BPWWdyUHRxc2tHN0UKOHBxYlppZHNCajlkeFVmSjl6T2Z4QkpsSHpXallUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWRCZ05WSFNVRQpGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFCkZnUVVJRzlXRmw0V0h5WGQ4VlRqRXVBckVpVjljQ2t3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQU1jUGdOZ3UKdzlXT0lLT1NZMFVJYWZRREpQOTJITSswNCttVjdxMWFGYS9wQWlBZnNiVlV1M1M5ZE90d1ZUaXdOUm9tQ1pjZQpXQ2hlMFljQ2t0RDdvZld5UlE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSVBsekRTRjBsK3Z3YVF2TTUzODZIREY1Rk8wYnJKRDArWW9Dbkt1bE8walRvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFdW1OYXJ3NDhwUmwzYlhMR3Q0WEUxWTJ6U3VtTC9FRHVDeUYvR25OTEdyeVptZzg1aUNzKwoycXlRYnNUeW1wdG1KMndHUDEzRlI4bjNNNS9FRW1VZk5RPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
      aggregatorCA:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJZRENDQVFhZ0F3SUJBZ0lSQU5lWG1sbVhTc29hWWhFaTMydlpCS013Q2dZSUtvWkl6ajBFQXdJd0FEQWUKRncweU5UQXlNakV3TXpRM016WmFGdzB6TlRBeU1Ua3dNelEzTXpaYU1BQXdXVEFUQmdjcWhrak9QUUlCQmdncQpoa2pPUFFNQkJ3TkNBQVNLKzhkS0hMSUZkeklOQ3kxbVBWZVFqeXVmT0VOcXc5dEdaQ2E1Vkt6N2JWaGZGb0FKCm44Q1NxZkRCdTQzbEFId3V0ako5TFJXK3FMMHpnVERxTlIzMm8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FvUXcKSFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpIUVlEVlIwT0JCWUVGT1JPOFhkVzlCaHVkQmNuREtzUnRSbENYY1JXTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDCklRQ3oveXlXb25RdjBFTkVDMGxSSnNjcVE3cGV0bXV2ejhYZ1RmeVJ2Qk94OFFJZ2V3NHpzT0JyTW5sckJBOFgKS29TYlVYYzByTmY2STNkS1I4TkpoancwRlVnPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUNwZ0NXY3ltQ2pzQStLbFJ4VnkveTNXNTB2dGRMR0NjcEtNT0oybEp5N2xvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFaXZ2SFNoeXlCWGN5RFFzdFpqMVhrSThybnpoRGFzUGJSbVFtdVZTcysyMVlYeGFBQ1ovQQprcW53d2J1TjVRQjhMcll5ZlMwVnZxaTlNNEV3NmpVZDlnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
      serviceAccount:
        key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlKS0FJQkFBS0NBZ0VBeHh0ZThHZUdCRGJQRTRFUUc5RFlDUDh2S2ZYZTVJK2hQZ3ZyeVJ6REJJWWlVYjlICmFnc1NYRUwrRE9JUUhQY05sQVd3c0NiV2kxeXVtaXJ0Rkpmd1FkYTFRalRHSE4vZXJtZW1qSUNRbk9veHhWR0QKb2ZpM3ZWdjhoNmQvZWVkS2lLeS9Xd3FzbjVmZ2JIdHBuNStpNXNsSzFTTmJlYkQ0UGJjZTRDOWgrQlIwK0FuVApLUCszcGlJKzcwdE9DZEdFTjVjRXJjVGlLejNGcEQxRkNkdUxkU2tUb1EwZjBJVGpsR0JvS1VVZm0wbXY5THFrCko0cmNlU2RiSHllaHZCSldiRU84REN4SWJ2cCtVMjhycXMwVmo1amp4SGlGYWl3RjNRV3FIOS9Ec2JKTVJ6Q3AKZTNURHI1dVhnaHRwbVQyMWZJSG1zczVjYlp4R3cvZG1kbEtReTAxbmlSK0pzYXdaZnliVStSeThtVzl3UWtkawpYVzhhK08vaGwvSU1MUnljSHhwbk1DdXRlYXJJWm52azVDR3IwUkNaejBhQnE4c3VZZXR0VWsrSU43bURrOEowCmZwNzcvUXJnQlkwdlFpY3d6TjlwS1RhTnJCSm1YNmhrdkgxQ0x1Q0p2OWVzVW9rV2graExoeW1QYWZOYXc5em8KOCtZZW54RXpRV1RUZCtYbFErc0JBVEZISFg2V2MwWTA4U2dFVTJrbVZzZi9JU2UxaTAyMENDVTFIajRRUXdyUgpSSkNkZFBZZGtNcWJmQ2JCOUFhWlJKREJJVUNXUzVBZm1TbDhaS2dMYVZBVlE0aWZlNnhOa2FSdkRwSUYrVXY0CmUydVRNSGExU2hjekhHWGdrSTlOQjdtUjB0Zmp5Q0ZNNXp3UVFXVVJRQkNYK0FZY24zemtpaW1Ca0VVQ0F3RUEKQVFLQ0FnQkc5ZVZQTHNZZnFGMEM2WU9STmt4WVlJSXhwVFFzSjFoaklhS0dDWjhqZEo2MG5jUlk4ZHM0VUpQMAppWGtPcWFvSU1FTDVkTTRQMnhkTFVMTXdITHArN0lPck5kM0ptcXZsWW9HRUg2bnFrcmpzUnhIdjN4RzFCaHlwClNEUHhnVklhQmQ4cEZsUFJpVEp0MTBvY25xdFRMemhoWC9tUkZGWlV3SGZibEdlSkg5bFVNVVExbjNXWFd5c3MKNDV6TGVRVnpQbnBuWi96blJsdXpIamNGdlY0bGdsOUJqY2poNndxazdmc1JnbFl5WlArMTYvTG5PT0U4dUo4TQpLbmJFN1pBcGc3WjRiQ3ZnaVp3T0psZmN4cnpCY2M3elRiVFcweHUvMnUzMzhDcnhvTWI0dEVvaStzbG5RNytxCm1oUjNqZnVwaFM1d1dZV3RkdjN0aDdYWHc3TmdjSlYwZWkxYWJ4emZvZTdzQm5RK1JETjlBTHB4bjA2TnNuZ2kKclY3M085dXFKRFRPZS9ZZ0hVdWVObUhnRGNZM1V0Z1dJblNUZmUzaXBvVSswblFSMW4vc1RMam8rR0sreEtSZworTzdKa1Zma3lUN1BlQTBxRHhmR3ZVNS9JN2dSVFBEU1J1UHlydHNVUjlmd1BULzZydm1wZTdUU0IrOFVONHVkCnZHdVhQZUtuZjIvUTU5VGtTaFBPekgwZUpvQW5pVFE4ajN5c3FVeTRHZml5RDRDeXRCTUJKdStpMlltUWo3dkcKRVc5RmY1YXJRcnBOdzJJS0p2T0pMRVh3VXdXd01TWTVNMmgxcjRFd1hVc0JjMzRUU1pEOHRndlRhNHdGdEx6UAp2ZGhIQjV1MXhTZUlOVlQ3V0R2TmFaR0RGdlJoU2tDODdEZ3dOMDFBbjBqdUp4QXQzUUtDQVFFQTZJWlNhNG4xCkVISTZGNTdYZnFlMlZhZ0Q5M2p1RUdMNHpRaitTV05JWmJ6NnFtVmdnRFRLaTVKdHdCMDF5UXVZT0pGOXRwaUkKWDZGNnJUZjBkVGhXK005cE1QNy9yZXpINjdIQU5KVFhpb0gwdWpjRkxuUG01WEFlMGV2QnQ5bFRIZnUvQ3dRYgppdUlWT281WThPMDFhVXpua0QxOUpzRnBKc3N5VmhMS3JQa2pxZ3JkTkpzMkNLMVNUZkFiM3FRbzIvZjMwY1ZkCklOaFZDYVlyNFgvMElUL3BaZDZVbGNSMHFETElWU252bUh0ellWRGZIUWF4UUZyVW52TlJrNjIyZ3VsQlo1MU4KdC9hanE0MlppV2RwOVc2OTZPcFlGRlhhbUFMK2U2RnU2SWpncDZySy9DaUFNRy93OFJJN1lNbGJRSmxaRkhyVQo5UnQrR0ZtZTVqaHZtd0tDQVFFQTJ6VmE5ci9HMFdOd2JuWWhDRkVqbGhqRVBxeVlnYndxV0JJNlduWTZiUWg4CkVRNzNpOFI4R05pSGhrS0UrWkJxakZqWUlIM0lYZ1Z3UGhFdTBING1NT2c0RUhGZUFLNVQzMGZRQ05OaDlvSTIKWndjbGhoVWZNSnBCRnNZdDJ0TGpaak9ucHNQTHJzY3hyMU5wb3BBSXBNc2ozY1VmOUp1citTa3YrSlphQkhUYwoxZnhEZmFUS0laSHJRQVFZTkJrdEJrdUo5aytObnI5NDVaOVFlWGg4WjdLcXk0MXpDZVJCbitLMzZ0akFoL1hlCmdXR3Y4K1o3SzJpTEF6T1NtUldYVTlTc2NiZWplMHFDZ2RqcTZqVDBraktHaldrendWZHQzVnFINTNWQ1RJelIKamZFenpEcEk1YWFSbTdmQkQwUjhLOVZaRlFaL3lRaXNCaHBBenVJdG53S0NBUUJ2bUUra0Z2RExkTmJXa1VCQgpKQUtKTjNxMzRZejN4bGc4SnczTGNOL0ZIQjU5ZXV3R2U4K2RqcWducEowMG9PRHNmVDhGVEUxZkFDUGRVRlo5Cmo0MkdHaDBWQzd6djN3elAzRjR2bmlPWDhPamdHaG5kZ25pVk11dEh1a3NkamlxcTREQisrL2l2L2ZOTVNCYjkKZ2dxNVA5UiswRlBwTHJmbGkyM2NDMmJELzBvVGlPVkRJeDZhcVh3dnRZWGFvNVNNaFlTbFk0QmZqQk83N3NsdQpqemMrWWVzRkhmN1hwaEtLeXR5RXF2eTNoTUFLTzRMbzdsWlJXWVpqeHNrbkJCN3MweisxbDdRK0R4dmI4TGg0ClRtNTNBVEFad2FhR0UvSTJOSEdvS2dFTmp1dXE3SGhBN3JzZkJBcHgyRnN4QjFKSlBZK1lHWjl0QjBYTUwrN24KOUx2ekFvSUJBUUMwVzhnR01YQkNJOUVEOGNubjcrcVp1ckxzNWxGc25RY3lBMzFqcE5jWmt0dVJwWURqekx4VwpMUUlFNDRKSlhCdHVja01SS0t6TlB5aEV5UnA5ak8yYlc5V1ZJZEc0T2Jia2hVK1RrMmlNekVJNnJ0U2U1NDRNCkRUNzBvQVptZnhGK3E0MkxWcG1scWxzazZEcUgrSDVFS0tmUDlqcitwWDd2dUlXeHdQTTdxM052MU9rcTNZVTUKN2JkanFuckhrdGRLMEtnb3N2ZlEzN1YzS0llc0NnaEJ3ZTFwSVc2L2VzREw3bHhvckFKdFcwekJvMENFS3VTNApxSUdJRnN6Tmk4aEF2MEZMSjA4cFIvcnRIeTdabU15SjVXeHp1VlZPQk1OdVZ1aHU5am1naGxSOHR6SnBIS09SCjRHVDVmRTBxWkt6TjIvSTVyR2xEWFJFOHpDajZqM245QW9JQkFBUEI1eTF4RlFhWUtiakplWldzZkpLUVkveDcKZldYa29WN0pSTGc0N2g3SnQvNS81NmFRK01pdDNIWHJvUjQ5S2ZhZXcwMGVHVHhXeUNNcUdPRVBGbitLMk0ydQp3V2YxYVNib2QyY0UrK2lNVWhwVytUTEpIYmRlTjkrbjNzYmdjazcyelZPNERnNlZDSTJsSDd0V09yQ0VlVys0CjBsQjdOZ3EwQnQwUE4zM0RrZ1FZWjQ2T3IyUW44NzFkcVArbGsrZ3IvRE4wM04rNTFYY3l3ek5aQlRVbzRIelEKN09ySjlaMlNpcW8yREcyTVlXVG5lVExNVnViWnR3SXQrdlJ0REVxUmhrUStsTnlWeHV1ME4wc21ySlFqNmFRaQpPY2VIYldCTi9JTXFmNDBuYk1raENITDFScEN1amhBTVg4RitDb3A4d0ZyaFFZTm5RQXFpN1ZsR1Z6MD0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K
      apiServer:
        image: registry.k8s.io/kube-apiserver:v1.32.2
        certSANs:
        - controlplane-0
        - controlplane-0.talos
        disablePodSecurityPolicy: true
        admissionControl:
        - name: PodSecurity
          configuration:
            apiVersion: pod-security.admission.config.k8s.io/v1alpha1
            defaults:
              audit: restricted
              audit-version: latest
              enforce: baseline
              enforce-version: latest
              warn: restricted
              warn-version: latest
            exemptions:
              namespaces:
              - kube-system
              runtimeClasses: []
              usernames: []
            kind: PodSecurityConfiguration
        auditPolicy:
          apiVersion: audit.k8s.io/v1
          kind: Policy
          rules:
          - level: Metadata
      controllerManager:
        image: registry.k8s.io/kube-controller-manager:v1.32.2
      proxy:
        image: registry.k8s.io/kube-proxy:v1.32.2
      scheduler:
        image: registry.k8s.io/kube-scheduler:v1.32.2
      discovery:
        enabled: true
        registries:
          kubernetes:
            disabled: true
          service: {}
      etcd:
        ca:
          crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJmekNDQVNTZ0F3SUJBZ0lSQU1IV0h1MWJhUG04R2VwMlo0RDFNNUF3Q2dZSUtvWkl6ajBFQXdJd0R6RU4KTUFzR0ExVUVDaE1FWlhSalpEQWVGdzB5TlRBeU1qRXdNelEzTXpaYUZ3MHpOVEF5TVRrd016UTNNelphTUE4eApEVEFMQmdOVkJBb1RCR1YwWTJRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFScWpudUd1N2d5CkpseEdydXlwQjAwdmwwUlZEMUFZM1V0NXdCNzQzUzJIM1kyZjg2M0JES2hiZlFmcWZ0Z2I4c0xBYTBUZHRhZjkKeXZ4YWVZTTNhdjZEbzJFd1h6QU9CZ05WSFE4QkFmOEVCQU1DQW9Rd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSApBd0VHQ0NzR0FRVUZCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRk04dmFscWxPUStBCjRYc1FoN0hXS1VKT1oyOVhNQW9HQ0NxR1NNNDlCQU1DQTBrQU1FWUNJUURRY0xjSkZOT0s4N1FZVk5LQSs4dkoKSnlQWS9sQlhnTmRRK1Yza1l1RkFPZ0loQU9YRE1yMnBQbnhvUFgyMW51Q0x2MHhuOUJOQW1tN29EVEZvYnlqNgo1TTc4Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
          key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUpRWVd4aDF0Z0JxQ0o0eHdKdVZzTUkyVExrNExWWGRWQ09xZ3lEbUlqZjdvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFYW81N2hydTRNaVpjUnE3c3FRZE5MNWRFVlE5UUdOMUxlY0FlK04wdGg5Mk5uL090d1F5bwpXMzBINm43WUcvTEN3R3RFM2JXbi9jcjhXbm1ETjJyK2d3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
      allowSchedulingOnControlPlanes: true
type: Opaque
