# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- providers/keycloak/provider.yaml
- providers/keycloak/deploymentruntimeconfig.yaml
- mrap.yaml

components:
- ../../../shared/components/crd-configurations

images:
- name: ghcr.io/crossplane-contrib/provider-keycloak
  newTag: v2.16.1@sha256:f7a4fb231f264ec3fb9d7983dadd3bbd98640230c426808a1d1cc993b508ce8d
