# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- providers/keycloak/provider.yaml
- providers/keycloak/deploymentruntimeconfig.yaml
- mrap.yaml

components:
- ../../../shared/components/crd-configurations

images:
- name: ghcr.io/crossplane-contrib/provider-keycloak
  newTag: v2.22.1@sha256:6e065ac6f7475b39e17559fa23554be4d4cdb80a18adca6f9bb4390e555af5c8
