# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- providers/keycloak/provider.yaml
- providers/keycloak/deploymentruntimeconfig.yaml
- mrap.yaml

components:
- ../../../shared/components/crd-configurations

images:
- name: ghcr.io/crossplane-contrib/provider-keycloak
  newTag: v2.19.0@sha256:c90c67b8cc04a4dc76800bb9dbb96801bd0f73dad031190613d259217a9fd0c0
