# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak

resources:
- namespace.yaml
- keycloak
- database.yaml
- gateway.yaml
- httproute.yaml
- crossplane/providerconfig.yaml
- home/realm.yaml
- home/groups.yaml
- home/roles.yaml

components:
- ../../../shared/components/crd-configurations

images:
- name: ghcr.io/cloudnative-pg/postgresql
  newTag: 18.4-standard-trixie@sha256:4e4ac3fb2c914cfb44f80f0b8be8aa550e83b80bf5220df49c3a8780c1f79bc8
