# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: application

resources:
- deployment.yaml
- gateway.yaml
- httproute.yaml
- pvc.yaml
- service.yaml
- bundle.yaml

images:
- name: ghcr.io/actualbudget/actual-server
  newTag: 26.5.0@sha256:b733ae30c70a66dc4d03577526e53575a0c04eab4f3ab6ace30934776251058c

configMapGenerator:
- name: actual-server-env
  literals:
  - ACTUAL_LOGIN_METHOD=openid
  - ACTUAL_ALLOWED_LOGIN_METHODS=openid
  - ACTUAL_OPENID_DISCOVERY_URL=
  - ACTUAL_OPENID_CLIENT_ID=actual
  - ACTUAL_OPENID_SERVER_HOSTNAME=https://
  - ACTUAL_OPENID_AUTH_METHOD=oauth2
