# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- ../../../../shared/components/strip-helm-labels
- ../../../../shared/components/k8s-digester

helmCharts:
- name: redis-operator
  repo: oci://ghcr.io/freshworks-oss/charts
  releaseName: redis-operator
  namespace: redis-operator
  version: 3.3.5
  valuesInline:
    image:
      repository: ghcr.io/freshworks-oss/redis-operator
      # renovate: datasource=docker depName=ghcr.io/freshworks-oss/redis-operator
      tag: v3.3.5@sha256:8620992f8a5863ad1bd8b64129319208f11cc6e051e65e500aff67f6b8062cb4
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        memory: 50Mi
    monitoring:
      enabled: true
      serviceMonitor: true
