apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  labels:
    app.kubernetes.io/component: redis
    app.kubernetes.io/instance: harbor
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: harbor
    redis-failover.freshworks.com/operator-group: redis-operator
  name: harbor
  namespace: harbor
spec:
  redis:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/component: redis
              app.kubernetes.io/instance: harbor
              app.kubernetes.io/name: harbor
              app.kubernetes.io/part-of: redis-failover
          topologyKey: kubernetes.io/hostname
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    exporter:
      enabled: true
      image: docker.io/oliver006/redis_exporter:v1.88.0-alpine@sha256:db6df2026585151c2209aa1f21c8856da883cf933b0943c0e51d1f4b3acf1a8d
    image: ghcr.io/valkey-io/valkey:9.0.0-alpine3.22@sha256:bef37d06d4856710973ee31dd1eac1482e4c8e6e7b847f999ad25433e646587b
    replicas: 3
    securityContext:
      fsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault
    storage:
      persistentVolumeClaim:
        apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          labels:
            app.kubernetes.io/name: redis
          name: data
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
          storageClassName: ssd-r1
  sentinel:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/component: sentinel
              app.kubernetes.io/instance: harbor
              app.kubernetes.io/name: harbor
              app.kubernetes.io/part-of: redis-failover
          topologyKey: kubernetes.io/hostname
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    exporter:
      enabled: true
      image: docker.io/oliver006/redis_exporter:v1.88.0-alpine@sha256:db6df2026585151c2209aa1f21c8856da883cf933b0943c0e51d1f4b3acf1a8d
    image: ghcr.io/valkey-io/valkey:9.0.0-alpine3.22@sha256:bef37d06d4856710973ee31dd1eac1482e4c8e6e7b847f999ad25433e646587b
    replicas: 3
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault
