apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: harbor
    app.kubernetes.io/name: database
    app.kubernetes.io/part-of: harbor
  name: harbor-db
  namespace: harbor
spec:
  affinity:
    podAntiAffinityType: required
  bootstrap:
    initdb:
      database: registry
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4-minimal-trixie@sha256:5e4fb4f7c9ce3a258d1946816bc6eebfb3d1e4cfd178b54e35a7ec97013a8473
  instances: 3
  storage:
    size: 10Gi
    storageClass: ssd-r1
