apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: harbor
    app.kubernetes.io/name: database
    app.kubernetes.io/part-of: harbor
  name: harbor-db
  namespace: harbor
spec:
  affinity:
    podAntiAffinityType: required
  bootstrap:
    initdb:
      database: registry
  imageName: ghcr.io/cloudnative-pg/postgresql:18.1-minimal-trixie@sha256:b09afc1667ed571b31ce35d633fc1139a6fd1a0a25a40546e1432f4d8370e91a
  instances: 3
  storage:
    size: 10Gi
    storageClass: ssd-r1
