apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: harbor
    app.kubernetes.io/name: database
    app.kubernetes.io/part-of: harbor
  name: harbor-db
  namespace: harbor
spec:
  affinity:
    podAntiAffinityType: required
  bootstrap:
    initdb:
      database: registry
  imageName: ghcr.io/cloudnative-pg/postgresql:18.3-minimal-trixie@sha256:59e50a79185bfde76057bfbc13b1ab3dd282d67b1a9d6a464b6d5234a2324730
  instances: 3
  storage:
    size: 10Gi
    storageClass: ssd-r1
