# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ezxss

resources:
- namespace.yaml
- database.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- gateway.yaml
- httproute.yaml

images:
- name: ghcr.io/gadgetmg/ezxss
  newTag: master@sha256:90e816394405050a6d1badd0a1cf7cd57bf5538aa977a08975a7d7d85e20b297
- name: ghcr.io/mariadb/mariadb
  newTag: 12.2.2-noble@sha256:71954573ee2d5d0a3658cf8d0bc4f34e87b90ffcd109752344ec6f29a49583ef
- name: ghcr.io/mariadb-operator/mariadb-operator
  newTag: 26.3.0@sha256:5ef5a5d35173b9be603970e7a1625100a0538004ddca984508df2c08c4fd5c72
- name: docker.io/prom/mysqld-exporter
  newTag: v0.19.0@sha256:eacb4b18e2ec1e0abdf2d64851b68526c964f6d9cb3e9458fb5d5f5062ea94c1

components:
- ../../../shared/components/crd-configurations
