# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ezxss

resources:
- namespace.yaml
- database.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- gateway.yaml
- httproute.yaml

images:
- name: ghcr.io/gadgetmg/ezxss
  newTag: master@sha256:90e816394405050a6d1badd0a1cf7cd57bf5538aa977a08975a7d7d85e20b297
- name: ghcr.io/mariadb/mariadb
  newTag: 12.1.2-noble@sha256:ef10d8048f5f87fe026eef417b91f3f5c1ed96773655fccced5cd8bc367b5922
- name: ghcr.io/mariadb-operator/mariadb-operator
  newTag: 25.10.4@sha256:f718727d22285a9b19b8340ec10a1e3a531133bfeb2af71df3a7faffffb4ea58
- name: docker.io/prom/mysqld-exporter
  newTag: v0.19.0@sha256:eacb4b18e2ec1e0abdf2d64851b68526c964f6d9cb3e9458fb5d5f5062ea94c1

components:
- ../../../shared/components/crd-configurations
