# yaml-language-server: $schema=../../../../schemas/cdi.kubevirt.io/cdi_v1beta1.json
apiVersion: cdi.kubevirt.io/v1beta1
kind: CDI
metadata:
  name: cdi
spec:
  config:
    scratchSpaceStorageClass: ssd-r1
    podResourceRequirements:
      requests:
        memory: 500M
      limits:
        memory: 1G
