# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/velero.io/schedule_v1.json
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: harbor-daily
  namespace: velero
spec:
  schedule: 0 5 * * *
  template:
    includedNamespaces:
    - harbor
    includedResources:
    - pvc
    labelSelector:
      matchExpressions:
      - key: app.kubernetes.io/component
        operator: In
        values:
        - jobservice
        - registry
  useOwnerReferencesInBackup: true
