apiVersion: v1
kind: Service
metadata:
  name: talos
  annotations:
    metallb.universe.tf/loadBalancerIPs: 172.18.0.10
spec:
  ports:
  - port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    kubevirt.io/vmpool: controlplane
  type: LoadBalancer
