# yaml-language-server: $schema=../../../../schemas/bitnami.com/sealedsecret_v1alpha1.json
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-db-s3-credentials
  namespace: harbor
spec:
  encryptedData:
    ACCESS_KEY_ID: AgBy39L/vOE9oeoJej7fGgMm9fui+mpQEQ4Zwrq8uxi+oEYoGQ7qROHmQlrkSS6mhsltwvynaKbDTm18xnqCDchOzdQXBymag41oJhUoEuQM+naIajFCeC52tiEz7FT7JtuQce/zRLjP/gGgLKD3AtR6YWQR7AxAl8+Mhhc0S0ppxhJnSbBgxnpQNDrsn0bZWBvwSEJA8U7AhZ1ucxZKhQ9CShhVdf/hZthU2pkzCA02c4DxUt2dVgl6JC7xKt5SzQh8J1IVcnv+qGl/iqtRlhkRtbdWdU3GyaFdV0LqsJRHhUKDSXL0EYldJi7ON4GFEsM8VB2DgmMmmNKwkW8QRe7cngmybVyKjCT4+MAHR+TDq/NEBh0QdqdBYntPOKDaz6Vu1RFMvhvApvDso4gVONxWL6ONGUT0OwTpFm5kpyRn6hX8uVdbOi3l6oqD7I4zwJ3uyd2zE1jeitYPlxyik1hVMJP43sMW/I+a+y+yf4CGpEHqJw0g3cR+HWpt9QgRdwazqBKlnFXw29cOITVW8MjNGs+kdPHs8tklqZ4vszpPqheOfysaGLTJea8HWrmeMHo3MkibxBdeAI8IieHqRianARGQCuxNpHno1MMsNfVJWCNVioKpyCbMdxvoJKWqV4UIsVqNxWvvtXMHY9vhXQ91hiaaWLkVg7VH8ljFRudQdh5pGwYGUY86mMjd8bi9XqHFg7eelNgINzPNZMROHLp2SwMm/w==
    ACCESS_SECRET_KEY: AgBqKyN4RwzzKssWoypvfWWbkPqzLS3knrApBfG+FptCLDiCLBUkL2QDbN3O+ldG18Kne6X0uxqjVUSdhrPbiY+c4iE+1AI+8VqSf6Ehx66dTmaeONoofAxkWEIOFN0jdEkLmmBJeJ86/kPH6WoQH4Uvm5wEhKAoVeh9W6SKyPwcYRSpT0+H+3tlGV35KzQUwidj4cSGLrubPD6hjuofyCTNVScPUdcLqVGDRP6nnRZRSvCwLFQYLQMxhLQvm9uFo4lIkIzbBaV0tLRYn2Sz8yZCENnxLWmwLFKXEDcPwHybBV25kRL9QspIzhbdD+LEpu+EkTIjv9jBYm1kUzmK3rHblf4Wn3zSGDYKv0SLhObzEL6nqr6OP3uOMr0OWOwGjY7//IX/2JpAZtpW4AQ4po74L+qO+sNz0QXlPhRhV+r6tZq/rxJx1fjiD3N2ND6LW+YCJT/dJ7q/sXUyUQTSUniQq+X1oRtFyDL7Kjc7u5pmW1joG8NyCIKj986g2eowMasbgsE6hIVKyj2v677uPzAgjZzMXXyVNluKAKRP9LLxjjxBOAq4ONmMj+dm0dg88WoEEUXTj9QgI6lDq/fcQ+TbCt3TxDv72+5KFQNrjDau0Y1uy+zRtd9BmW1EeTBpN4InWs6Ghap3sJhUbxaVEwQ5aNI/PWg29YMGpnn1SKYYAEri79fEcUMIECoTQAX6gnDQtxGLIFHfGNsWcav0h3by3clbygak93gq/o1xyR5eEwU68qNw4JH3
  template:
    metadata:
      name: harbor-db-s3-credentials
      namespace: harbor
    type: Opaque
