# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: harbor

resources:
- namespace.yaml
- gateway.yaml
- httproute.yaml
- core
- database
- jobservice
- portal
- redis
- registry
- trivy
- keycloak

components:
- ../../../shared/components/crd-configurations

configMapGenerator:
- name: harbor-common
  literals:
  - CORE_URL=http://harbor-core:80
  - LOG_LEVEL=info
  - REGISTRY_CONTROLLER_URL=http://harbor-registry:8080
  - REGISTRY_CREDENTIAL_USERNAME=harbor_registry_user
  - REGISTRY_URL=http://harbor-registry:5000
  - TOKEN_SERVICE_URL=http://harbor-core:80/service/token
- name: harbor-config-override-template
  options:
    disableNameSuffixHash: true
  literals:
  - auth_mode=oidc_auth
  - primary_auth_mode=true
  - project_creation_restriction=adminonly
  - read_only=false
  - token_expiration=30
  - oidc_name=seigra.net
  - oidc_endpoint=https://auth.seigra.net/realms/home
  - oidc_extra_redirect_parms={}
  - oidc_client_id=harbor
  - oidc_groups_claim=groups
  - oidc_admin_group=admin
  - oidc_scope=openid
  - oidc_verify_cert=true
  - oidc_auto_onboard=true
  - oidc_user_claim=email
  - robot_token_duration=30
  - robot_name_prefix=robot$
  - audit_log_forward_endpoint=""
  - skip_audit_log_database=false
  - scanner_skip_update_pulltime=true
  - banner_message=""

labels:
- pairs:
    app.kubernetes.io/instance: harbor
    app.kubernetes.io/part-of: harbor
  includeSelectors: true
  includeTemplates: true

replicas:
- name: harbor-core
  count: 2
- name: harbor-jobservice
  count: 2
- name: harbor-portal
  count: 2
- name: harbor-registry
  count: 2
- name: harbor-trivy
  count: 2

images:
- name: ghcr.io/cloudnative-pg/postgresql
  newTag: 18.3-minimal-trixie@sha256:8d3183ef537b17efbb2e6e6665852a7c0d8dc4a3f3b91c11f0e8a2d056799880
- name: ghcr.io/goharbor/harbor-core
  newTag: v2.15.1@sha256:887a85b8ea98b76bfc9f715f1a0785bb99f9a1034241513902dd6e95be922a83
- name: ghcr.io/goharbor/harbor-jobservice
  newTag: v2.15.1@sha256:0de4fd2ce3a02d3e6591b439e4674ea085885ddf43652b44004cc67eb19dba12
- name: ghcr.io/goharbor/harbor-portal
  newTag: v2.15.0@sha256:541d5fa95bf77240d46a438f86245cdfd6afa6dd7fdd0cf4dd4c905af6a980b1
- name: ghcr.io/goharbor/harbor-registryctl
  newTag: v2.15.1@sha256:554147a956989175f63f8d41573d716c6ddf6052acd1749c88c0f99ce6ee2bff
- name: ghcr.io/goharbor/registry-photon
  newTag: v2.15.0@sha256:beb49fd16cf0906c04a2bf51a22f7210289e7cc2ae43a733e2a0364380aceae6
- name: ghcr.io/goharbor/trivy-adapter-photon
  newTag: v2.15.1@sha256:f0c52bed36c083ec4fded26cefab01e4cd58c9354c261cb3156c69f57bb50131
- name: docker.io/oliver006/redis_exporter
  newTag: v1.83.0-alpine@sha256:7643b705adca0ef5c700cae28cfd8798c3d3b653ef17096084359d17b70ea5ca
- name: ghcr.io/valkey-io/valkey
  newTag: 9.0.0-alpine3.22@sha256:bef37d06d4856710973ee31dd1eac1482e4c8e6e7b847f999ad25433e646587b
