# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: harbor

resources:
- namespace.yaml
- gateway.yaml
- httproute.yaml
- core
- database
- jobservice
- portal
- redis
- registry
- trivy
- keycloak

components:
- ../../../shared/components/crd-configurations

configMapGenerator:
- name: harbor-common
  literals:
  - CORE_URL=http://harbor-core:80
  - LOG_LEVEL=info
  - REGISTRY_CONTROLLER_URL=http://harbor-registry:8080
  - REGISTRY_CREDENTIAL_USERNAME=harbor_registry_user
  - REGISTRY_URL=http://harbor-registry:5000
  - TOKEN_SERVICE_URL=http://harbor-core:80/service/token
- name: harbor-config-override-template
  options:
    disableNameSuffixHash: true
  literals:
  - auth_mode=oidc_auth
  - primary_auth_mode=true
  - project_creation_restriction=adminonly
  - read_only=false
  - token_expiration=30
  - oidc_name=seigra.net
  - oidc_endpoint=https://auth.seigra.net/realms/home
  - oidc_extra_redirect_parms={}
  - oidc_client_id=harbor
  - oidc_groups_claim=groups
  - oidc_admin_group=admin
  - oidc_scope=openid
  - oidc_verify_cert=true
  - oidc_auto_onboard=true
  - oidc_user_claim=email
  - robot_token_duration=30
  - robot_name_prefix=robot$
  - audit_log_forward_endpoint=""
  - skip_audit_log_database=false
  - scanner_skip_update_pulltime=true
  - banner_message=""

labels:
- pairs:
    app.kubernetes.io/instance: harbor
    app.kubernetes.io/part-of: harbor
  includeSelectors: true
  includeTemplates: true

replicas:
- name: harbor-core
  count: 2
- name: harbor-jobservice
  count: 2
- name: harbor-portal
  count: 2
- name: harbor-registry
  count: 2
- name: harbor-trivy
  count: 2

images:
- name: ghcr.io/cloudnative-pg/postgresql
  newTag: 18.4-minimal-trixie@sha256:7a91b8daee8589f4825b50da23ed545b57c43a126016af573cbdf5e424d6c2f6
- name: ghcr.io/goharbor/harbor-core
  newTag: v2.15.1@sha256:887a85b8ea98b76bfc9f715f1a0785bb99f9a1034241513902dd6e95be922a83
- name: ghcr.io/goharbor/harbor-jobservice
  newTag: v2.15.0@sha256:a22c7cccba4673b26ffb96f5c37971d85d879dd837bc82448e01c0170b68cf28
- name: ghcr.io/goharbor/harbor-portal
  newTag: v2.15.0@sha256:541d5fa95bf77240d46a438f86245cdfd6afa6dd7fdd0cf4dd4c905af6a980b1
- name: ghcr.io/goharbor/harbor-registryctl
  newTag: v2.15.1@sha256:554147a956989175f63f8d41573d716c6ddf6052acd1749c88c0f99ce6ee2bff
- name: ghcr.io/goharbor/registry-photon
  newTag: v2.15.1@sha256:ebf0325c2661729dbb317cbf839608eb8b15cfa158911a94976f2c21563c466e
- name: ghcr.io/goharbor/trivy-adapter-photon
  newTag: v2.15.1@sha256:f0c52bed36c083ec4fded26cefab01e4cd58c9354c261cb3156c69f57bb50131
- name: docker.io/oliver006/redis_exporter
  newTag: v1.84.0-alpine@sha256:9f382eef9bff285d41d03c15c1dc9c889ab75687bea248d5fa0318efa08069d9
- name: ghcr.io/valkey-io/valkey
  newTag: 9.0.0-alpine3.22@sha256:bef37d06d4856710973ee31dd1eac1482e4c8e6e7b847f999ad25433e646587b
